### PR TITLE
Light/dark mode

### PR DESCRIPTION
**Pull request by DillonB07**
This will change to light/dark mode dependent on system theme

### CODE REVIEW

**Comment by DillonB07** [comment]
Don't merge yet. Somehow I messed up the avatar displaying

**Comment by JBYT27** [comment]
Oh, okay! 

> It could be the `h1.title` switching to `.title` maybe?

**Comment by DillonB07** [comment]
No, it's not that. It's the link not being passed to the `src` attribute. Also, the use is being displayed as `None`.
Screenshot 2021-12-12 at 17 48 49

**Comment by DillonB07** [comment]
This is in the same repl as yesterday if you want to hop in.

**Comment by JBYT27** [comment]
Okay. So on the original `main` branch, the styling is *completely* off, and I don't really know why yet.

Screenshot 2021-12-12 12 51 34 PM

**Comment by DillonB07** [comment]
Can you invite me to the repl? I'll have a look at what's going on there.

**Comment by JBYT27** [comment]
Sure thing.

**Comment by DillonB07** [comment]
About the flask_session issue, maybe just cross that bridge when it comes to it.

Created a suggestion on Canny for [Auto-pulling from GitHub](https://replit.canny.io/general-feedback/p/allow-auto-pulling-from-github). If it actually gets implemented(unlikely), then we can use GitHub actions to delete and remake the folder once a day or something like that. Alternatively, you could switch to using Replit for developing it and another platform for hosting it.

**Comment by JBYT27** [comment]
Oh, okay!

**Comment by JBYT27** [comment]
I'll check real quick and see if it looks good!

**Comment by JBYT27** [comment]
So I'm not sure if you can switch this, but the github logo doesn't really change so it's hard to see it, and is there a dark/light mode button?

**Comment by JBYT27** [comment]
Also, that's the same with the card, it's hard to see, so if it's possible (I'll edit it later if you want), could you also apply the CSS dark/light mode rule to the card as well?

**Comment by DillonB07** [comment]
There's not a button. It changes automatically depending on the user's computer theme. You can see the a gif below of me demo-ing it.

I can't really do anything about the logo. It's the same on GitHub dark mode with their favicon. There aren't any variants of it for dark mode.

Yep I'll fix the cards I missed that bit.

**Comment by DillonB07** [comment]
Cards should be sorted now
Screenshot 2021-12-13 at 18 37 33
Screenshot 2021-12-13 at 18 37 51

**Comment by JBYT27** [comment]
Ooh, that makes sense, I was wondering why there wasn't a button lol.

Okay, thanks! I'll merge now :D

**Review by JBYT27 — APPROVED** [review]
chore: approve

**Comment by DillonB07** [comment]
> I was wondering why there wasn't a button lol.

I did try and do some JavaScript to make a button at first but then realised that it would be much simpler to just use CSS.
*If it isn't clear, I don't really know JS*

**Comment by JBYT27** [comment]
Oh, okay. No problem, I was just curious

**Comment by JBYT27** [comment]
Hey @DillonB07, I'm gonna post it now! Again, thanks so much for helping with this project!

**Pull request merged**
